/**
 * model-value — evidence-based roster guidance.
 *
 * Reads the telemetry ledger that every council review appends to and ranks each model
 * by the signal a council exists to produce: unique insight (the "gold"), theme coverage,
 * reliability, and cost. Turns roster curation from vibes into data — the complement to
 * the roster-freshness check (freshness says "a newer model exists"; this says "...and your
 * current one is dead weight / punches above its tier").
 *
 * Usage: tsx scripts/model-value.ts [--path <jsonl>] [--min-runs N]
 */
import { aggregateModelValue, ModelValueRow } from "../src/lib/telemetry";
import { loadTelemetry, TELEMETRY_PATH } from "../src/lib/telemetry-ledger";
import { loadFeedbackLedger } from "../src/lib/feedback-ledger";
import { summarizeFeedback } from "../src/lib/feedback";
import { aggregateRedundancy } from "../src/lib/similarity";

function arg(flag: string): string | null {
  const i = process.argv.indexOf(flag);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : null;
}

function fmtCost(n: number): string {
  return n < 0.01 ? `$${n.toFixed(4)}` : `$${n.toFixed(2)}`;
}

function row(r: ModelValueRow): string {
  const theme = r.themeAvg === null ? "—" : r.themeAvg.toFixed(1);
  const cpi = r.costPerInsight === null ? "—" : fmtCost(r.costPerInsight);
  const rel = `${(r.successRate * 100).toFixed(0)}%${r.fallbacks ? ` (${r.fallbacks}fb)` : ""}`;
  return `| ${r.name} | ${r.tier} | ${r.appearances} | ${r.uniquePerRun.toFixed(2)} | ${theme} | ${rel} | ${fmtCost(r.totalCost)} | ${cpi} | ${r.verdict} |`;
}

function main(): void {
  const path = arg("--path") || undefined;
  const minRuns = Number.parseInt(arg("--min-runs") || "1", 10);

  const runs = loadTelemetry(path);
  if (runs.length === 0) {
    console.log(`No telemetry yet at ${path || TELEMETRY_PATH}.\nRun some plan reviews — each appends one record — then re-run this report.`);
    return;
  }

  // Human votes (npm run feedback) weight the ranking once there are enough of them.
  const rows = aggregateModelValue(runs, summarizeFeedback(loadFeedbackLedger())).filter((r) => r.appearances >= minRuns);
  const span = `${runs.length} review${runs.length === 1 ? "" : "s"}`;
  const lowConfidence = runs.length < 5;

  const out: string[] = [];
  out.push(`# Model value report — ${span}`);
  out.push("");
  if (lowConfidence) {
    out.push(`> ⚠️ Only ${span} on record — early signal, not yet conclusive. Confidence grows past ~5–10 reviews.`);
    out.push("");
  }
  out.push("Ranked by composite value (unique insight weighted highest, then coverage, gated by reliability).");
  out.push("");
  out.push("| Model | tier | runs | gold/run | theme | reliab. | cost | $/insight | verdict |");
  out.push("|---|---|--:|--:|--:|--:|--:|--:|---|");
  for (const r of rows) out.push(row(r));
  out.push("");
  out.push("- **gold/run** = significance-weighted unique insights per appearance (high=3, med=2, low=1) — the core council signal.");
  out.push("- **theme** = mean coverage depth across themes (0–3). **$/insight** = total spend ÷ gold (lower is better value).");
  out.push("");

  // Actionable callouts.
  const swaps = rows.filter((r) => r.verdict.startsWith("🔻") || r.verdict.startsWith("🔴"));
  const bargains = rows.filter((r) => r.verdict.startsWith("🌟"));
  if (swaps.length) {
    out.push(`### 🔻 Swap candidates`);
    for (const r of swaps) out.push(`- **${r.name}** \`${r.id}\` — ${r.verdict.replace(/^\S+ /, "")} (gold/run ${r.uniquePerRun.toFixed(2)}, reliab ${(r.successRate * 100).toFixed(0)}%)`);
    out.push("");
  }
  if (bargains.length) {
    out.push(`### 🌟 Keep / promote`);
    for (const r of bargains) out.push(`- **${r.name}** \`${r.id}\` — gold/run ${r.uniquePerRun.toFixed(2)}, ${fmtCost(r.totalCost)} total`);
    out.push("");
  }
  // Redundancy: pairs whose responses are near-duplicates run after run are one
  // vote, not two — drop one and spend the slot on a distinct family.
  const redundant = aggregateRedundancy(runs.filter((r) => r.similarity).map((r) => ({ pairs: r.similarity!.pairs })));
  if (redundant.length) {
    out.push(`### 👯 Redundant pairs (near-identical responses over ≥3 runs)`);
    for (const p of redundant) out.push(`- \`${p.a}\` ~ \`${p.b}\` — mean similarity ${p.meanScore.toFixed(2)} over ${p.runs} runs → keep one`);
    out.push("");
  }
  out.push("---");
  out.push("_Generated by `scripts/model-value.ts` from the telemetry ledger. Edit rosters in `src/lib/rosters.ts`._");

  console.log(out.join("\n"));
}

main();
