#!/usr/bin/env tsx
// Post a review's findings to a GitHub pull request as inline review comments.
//
//   GITHUB_TOKEN=ghp_... npm run post-pr-review -- --findings docs/plans/reviews/x.findings.json \
//       --repo owner/name --pr 123 [--min-severity high] [--max 25] [--dry-run] [--event COMMENT|REQUEST_CHANGES]
//
// The findings file is written by `npm run review` in structured mode. A finding
// whose `location` looks like `path:line` (or `path:start-end`) becomes an inline
// comment on that line of the PR diff when the file is part of the PR; everything
// else is folded into the review body. Findings keep their stable ids, so a
// re-run after fixes can be compared with `review-compare`.
import * as fs from "fs";

interface ExportedCluster {
  id: string;
  claim: string;
  severity: string;
  category: string;
  location?: string;
  families: string[];
  models: string[];
  recommendation?: string;
  evidence?: string;
}
interface FindingsExport {
  plan: string;
  contentHash: string;
  totalFamilies: number;
  clusters: ExportedCluster[];
}

const SEVERITY_RANK: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1, info: 0 };

function arg(flag: string): string | null {
  const i = process.argv.indexOf(flag);
  return i !== -1 && i + 1 < process.argv.length ? process.argv[i + 1] : null;
}

export function parseLocation(location: string | undefined): { path: string; line: number } | null {
  if (!location) return null;
  const m = /^([\w./@-]+\.[A-Za-z0-9]+):(\d+)(?:-(\d+))?/.exec(location.trim());
  if (!m) return null;
  return { path: m[1], line: Number(m[2]) };
}

export function buildReviewBody(exp: FindingsExport, general: ExportedCluster[]): string {
  const lines = [
    `## Model Prism council review — ${exp.plan}`,
    "",
    `${exp.clusters.length} finding cluster(s) across ${exp.totalFamilies} model families. Inline comments carry the findings tied to a file and line; the rest are below.`,
    "",
  ];
  for (const c of general) {
    lines.push(`- **[${c.severity}] [${c.category}]** ${c.claim} \`${c.id}\` _(${c.families.length}/${exp.totalFamilies} families)_`);
    if (c.recommendation) lines.push(`  - Fix: ${c.recommendation}`);
  }
  lines.push("", "---", "_Generated by [Model Prism](https://github.com/loftsshuki/model-prism)_");
  return lines.join("\n");
}

async function gh<T>(token: string, method: string, url: string, body?: unknown): Promise<T> {
  const res = await fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(body ? { "Content-Type": "application/json" } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(30_000),
  });
  if (!res.ok) throw new Error(`GitHub ${method} ${url} → ${res.status} ${(await res.text()).slice(0, 200)}`);
  return (await res.json()) as T;
}

async function main(): Promise<number> {
  const findingsPath = arg("--findings");
  const repo = arg("--repo");
  const pr = Number(arg("--pr"));
  if (!findingsPath || !repo || !Number.isFinite(pr)) {
    console.error("Usage: npm run post-pr-review -- --findings <file.findings.json> --repo owner/name --pr <number> [--min-severity high] [--max 25] [--dry-run]");
    return 2;
  }
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN || "";
  const dryRun = process.argv.includes("--dry-run");
  if (!token && !dryRun) { console.error("GITHUB_TOKEN is required (or pass --dry-run)."); return 2; }

  let exp: FindingsExport;
  try {
    exp = JSON.parse(fs.readFileSync(findingsPath, "utf-8"));
  } catch (e) {
    console.error(`Could not read findings file: ${(e as Error).message}`);
    return 2;
  }
  const minSev = SEVERITY_RANK[arg("--min-severity") ?? "medium"] ?? 2;
  const max = Number(arg("--max") ?? 25);
  const event = (arg("--event") ?? "COMMENT").toUpperCase();

  const eligible = exp.clusters
    .filter((c) => (SEVERITY_RANK[c.severity] ?? 0) >= minSev)
    .sort((a, b) => (SEVERITY_RANK[b.severity] ?? 0) - (SEVERITY_RANK[a.severity] ?? 0) || b.families.length - a.families.length)
    .slice(0, max);

  // Only files in the PR diff can take inline comments.
  let prFiles = new Set<string>();
  if (!dryRun) {
    const files = await gh<Array<{ filename: string }>>(token, "GET", `https://api.github.com/repos/${repo}/pulls/${pr}/files?per_page=100`);
    prFiles = new Set(files.map((f) => f.filename));
  }

  const comments: Array<{ path: string; line: number; side: "RIGHT"; body: string }> = [];
  const general: ExportedCluster[] = [];
  for (const c of eligible) {
    const loc = parseLocation(c.location);
    if (loc && (dryRun || prFiles.has(loc.path))) {
      comments.push({
        path: loc.path, line: loc.line, side: "RIGHT",
        body: `**[${c.severity}] [${c.category}]** ${c.claim}\n\n${c.recommendation ? `Fix: ${c.recommendation}\n\n` : ""}_${c.families.length}/${exp.totalFamilies} model families · \`${c.id}\`_`,
      });
    } else {
      general.push(c);
    }
  }
  const body = buildReviewBody(exp, general);

  if (dryRun) {
    console.log(`[dry-run] would post ${comments.length} inline comment(s) and ${general.length} general finding(s) to ${repo}#${pr} (event ${event})`);
    for (const c of comments) console.log(`  ${c.path}:${c.line}  ${c.body.split("\n")[0]}`);
    console.log("\n" + body);
    return 0;
  }

  // Inline comments can be rejected when a line is outside the diff hunks; fall
  // back to a body-only review so the findings still land.
  try {
    await gh(token, "POST", `https://api.github.com/repos/${repo}/pulls/${pr}/reviews`, { event, body, comments });
    console.log(`Posted review with ${comments.length} inline comment(s) to ${repo}#${pr}`);
  } catch (e) {
    console.error(`Inline review rejected (${(e as Error).message.slice(0, 160)}); posting body-only review.`);
    const merged = buildReviewBody(exp, [...general, ...eligible.filter((c) => !general.includes(c))]);
    await gh(token, "POST", `https://api.github.com/repos/${repo}/pulls/${pr}/reviews`, { event, body: merged });
    console.log(`Posted body-only review to ${repo}#${pr}`);
  }
  return 0;
}

if (process.argv[1] && /post-pr-review\.ts$/.test(process.argv[1])) {
  main().then((code) => process.exit(code)).catch((e) => { console.error(e); process.exit(1); });
}
