/**
 * review-digest — surface patterns across every council review.
 *
 * Reads the review-findings ledger (each review appends one record) and answers the
 * questions a pile of scattered .review.md files can't: which plans still have unresolved
 * disagreements, what blind spots keep recurring, and how findings/cost trend over time.
 * The content counterpart to `model-value` (which ranks models, not findings).
 *
 * Usage: tsx scripts/review-digest.ts [--path <jsonl>] [--recent N]
 */
import { loadReviewLedger, REVIEW_LEDGER_PATH, ReviewRecord } from "../src/lib/review-ledger";

function arg(flag: string): string | null {
  const i = process.argv.indexOf(flag);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : null;
}

const STOP = new Set("the a an and or of to in for on is are be it its with as that this whether how no none not model models council plan plans review can could would should any most some none about across only also more than into other their there what when which from have has had will must may even given beyond per them they when where while been being does done such very each both either neither".split(" "));

function blindSpotKeywords(records: ReviewRecord[], top: number): Array<[string, number]> {
  const counts = new Map<string, number>();
  for (const r of records) {
    for (const b of r.blindSpots) {
      const seen = new Set<string>();
      for (const w of b.toLowerCase().split(/[^a-z0-9]+/)) {
        if (w.length < 4 || STOP.has(w) || seen.has(w)) continue;
        seen.add(w);
        counts.set(w, (counts.get(w) ?? 0) + 1);
      }
    }
  }
  return [...counts.entries()].filter(([, n]) => n >= 2).sort((a, b) => b[1] - a[1]).slice(0, top);
}

function main(): void {
  const ledgerPath = arg("--path") || undefined;
  const recentN = Number.parseInt(arg("--recent") || "8", 10);
  const records = loadReviewLedger(ledgerPath);

  if (records.length === 0) {
    console.log(`No reviews captured yet at ${ledgerPath || REVIEW_LEDGER_PATH}.\nRun some plan reviews — each appends one record — then re-run this digest.`);
    return;
  }

  const sorted = [...records].sort((a, b) => a.ts.localeCompare(b.ts));
  const totalCost = records.reduce((s, r) => s + r.cost, 0);
  const totalDis = records.reduce((s, r) => s + r.disagreements.length, 0);
  const totalBlind = records.reduce((s, r) => s + r.blindSpots.length, 0);

  const out: string[] = [];
  out.push(`# Review digest — ${records.length} review${records.length === 1 ? "" : "s"}`);
  out.push("");
  out.push(`Span: ${sorted[0].ts.slice(0, 10)} → ${sorted[sorted.length - 1].ts.slice(0, 10)} · total spend $${totalCost.toFixed(2)} · ${totalDis} contested points · ${totalBlind} blind spots`);
  out.push(`Averages per review: ${(totalDis / records.length).toFixed(1)} contested · ${(totalBlind / records.length).toFixed(1)} blind spots · $${(totalCost / records.length).toFixed(3)}`);
  out.push("");

  // Plans with the most unresolved disagreement — these are the decisions you still owe.
  const contested = records.filter((r) => r.disagreements.length > 0).sort((a, b) => b.disagreements.length - a.disagreements.length).slice(0, recentN);
  if (contested.length > 0) {
    out.push("## ⚖️ Plans with unresolved disagreement (decisions owed)");
    for (const r of contested) {
      out.push(`- **${r.plan}** (${r.disagreements.length}) — ${r.disagreements.map((d) => d.topic).join("; ")}`);
    }
    out.push("");
  }

  // Recurring blind-spot themes — what the council keeps noticing your plans miss.
  const kw = blindSpotKeywords(records, 14);
  if (kw.length > 0) {
    out.push("## 🔁 Recurring blind-spot themes");
    out.push(`_Words appearing in blind spots across ≥2 reviews — the gaps your plans keep leaving:_`);
    out.push("");
    out.push(kw.map(([w, n]) => `\`${w}\`×${n}`).join("  "));
    out.push("");
  }

  // Most recent reviews at a glance.
  out.push("## 🕑 Recent reviews");
  for (const r of [...sorted].reverse().slice(0, recentN)) {
    out.push(`- ${r.ts.slice(0, 10)} **${r.plan}** [${r.roster}] — ${r.modelsSucceeded} models, ${r.disagreements.length} contested, ${r.blindSpots.length} blind spots, $${r.cost.toFixed(2)}`);
  }
  out.push("");
  out.push("---");
  out.push("_Generated by `scripts/review-digest.ts` from the review-findings ledger._");
  console.log(out.join("\n"));
}

main();
